# Generated by Django 3.0.2 on 2020-01-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicinalData', '0002_advice_dosage_linktable_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosage',
            name='med_type',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
