# Generated by Django 3.0.2 on 2020-01-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicinalData', '0005_auto_20200130_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage',
            name='amount',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
